version: "3"
services:
  web:
    build: "."
    volumes:
      - ".:/usr/src/app"
    ports:
      - "8000:8000"
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
      ENV: "development"
    env_file:
      - .env

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - "./docker/db/pgdata:/var/lib/postgresql/data"
    env_file:
      - .env
