version: 2
jobs:
  build:
    docker:
      - image: python:3.6

    steps:
      - checkout
      - cd ~/promofinder-backend/

      # Download and cache dependencies
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
  test:
    steps:
      - checkout
      - run: mkdir test-reports/
      - cd ~/promofinder-backend/
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pip install -r requirements.txt
            py.test -vv --junitxml=test-reports/output.xml

      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/

  deploy:
    - steps:
      - run:
        name: Deploy Heroku
        command: |
          heroku maintenance:on --app $HEROKU_APP_NAME
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
          heroku restart --app $HEROKU_APP_NAME
          heroku maintenance:off --app HEROKU_APP_NAME
