version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ./venv

      - run:
          name: run tests
          command: |
            source venv/bin/activate
            py.test -vv

  deploy:
    - steps:
      - run:
        name: Deploy Heroku
        command: |
          heroku maintenance:on --app $HEROKU_APP_NAME
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
          heroku restart --app $HEROKU_APP_NAME
          heroku maintenance:off --app HEROKU_APP_NAME
